name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Basic Configuration
          user: ${{ github.repository_owner }}
          template: classic
          base: header, community, repositories, metadata
          
          # Languages
          plugin_languages: yes
          plugin_languages_section: most-used
          plugin_languages_limit: 6
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact

          # Streaks
          plugin_streak: yes
          
          # Lines of code
          plugin_lines: yes
          
          # Activity graph
          plugin_activity: yes
          
          # Notable repos
          plugin_repositories: yes
          plugin_repositories_featured: SoundWrapped,StudyAssistant
